# Generated by Django 4.0.6 on 2022-09-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_performance_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='roi',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
